### ISSUE TITLE
lwgps在rtt studio中打开后，软件包被下载，但是未被rtt加入编译

### ISSUE THREAD

**Issue by HikerPan** [orange2348/lwgps2rtt#1]
你好
如下图所示，lwgps已经打开。
但是在RTT sutdio中为灰色，一直无法被编译。
![1](https://user-images.githubusercontent.com/34146874/94359266-ab314180-00d8-11eb-91ec-8ed046dfc051.png)

**Comment by orange2348** [comment]
我是使用的ENV下menuconfig配置好后，然后包更新，使用SCons生成IAR工程来跑的，代码能够正确的加入的工程里面的。RTT studio没有使用过，可能回复不了你的问题。

**Comment by HikerPan** [comment]
我试了在ENV下，使用QEMU也没有能够加入编译

**Comment by orange2348** [comment]
我用RTT studio试了下，是可以正常加入构建的，如在论坛回复的，你文件夹上面的图标表示此部分从构建中排除，你可以手动将此部分调整下。
![image](https://user-images.githubusercontent.com/11645253/95645077-46211700-0aee-11eb-9092-58b4f97dbe6c.png)
